import { useEffect } from 'react';
import { StyleSheet, View } from 'react-native';
import { Text, ActivityIndicator } from 'react-native-paper';
import { useRoute } from '@react-navigation/native';
import type { RouteProp } from '@react-navigation/native';

import { colors, spacing, typography } from '@/core/theme';
import { getErrorMessage } from '@/data/api/client';
import type { RootStackParamList } from '@/navigation/types';
import AppButton from '@/presentation/components/AppButton';
import AppCard from '@/presentation/components/AppCard';
import MarkdownRenderer from '@/presentation/components/MarkdownRenderer';
import NoteTypeBadge from '@/presentation/components/NoteTypeBadge';
import ScreenWrapper from '@/presentation/components/ScreenWrapper';
import TopicTags from '@/presentation/components/TopicTags';
import { useNotesStore } from '@/store/notesStore';
import { useUIStore } from '@/store/uiStore';

type Route = RouteProp<RootStackParamList, 'NoteDetail'>;

function formatNoteContent(content: string): string {
  return content
    .replace(/^#{1,6}\s+/gm, '')
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/^\s*[-*]\s+/gm, '• ')
    .trim();
}

function providerLabel(note: { ai_metadata?: { provider?: string | null; model?: string | null } | null }) {
  const provider = note.ai_metadata?.provider;
  if (!provider || provider === 'local') return 'Local template (add OpenAI/Gemini API key for AI answers)';
  if (provider === 'openai') return `Generated by ChatGPT (${note.ai_metadata?.model ?? 'OpenAI'})`;
  if (provider === 'gemini') return `Generated by Google Gemini (${note.ai_metadata?.model ?? 'Gemini'})`;
  return `Generated by ${provider}`;
}

export default function NoteDetailScreen() {
  const route = useRoute<Route>();
  const { noteId } = route.params;
  const { selectedNote, isLoading, isExporting, fetchNote, exportNotePdf } = useNotesStore();
  const showSnackbar = useUIStore((s) => s.showSnackbar);

  useEffect(() => {
    fetchNote(noteId);
  }, [noteId, fetchNote]);

  const handleExportPdf = async () => {
    try {
      await exportNotePdf(noteId);
      showSnackbar('PDF ready to share or save', 'success');
    } catch (err) {
      showSnackbar(getErrorMessage(err), 'error');
    }
  };

  if (isLoading || !selectedNote) {
    return (
      <View style={styles.centered}>
        <ActivityIndicator size="large" color={colors.primary} />
      </View>
    );
  }

  const note = selectedNote;

  return (
    <ScreenWrapper>
      <View style={styles.header}>
        <NoteTypeBadge type={note.type} />
        <Text style={styles.title}>{note.title}</Text>
        <Text style={styles.provider}>{providerLabel(note)}</Text>

        {note.summary ? (
          <AppCard style={styles.summaryCard}>
            <Text style={styles.summaryLabel}>Summary</Text>
            <Text style={styles.summaryText}>{note.summary}</Text>
          </AppCard>
        ) : null}
      </View>

      <TopicTags topics={note.topics ?? []} showLabel />

      <AppCard style={styles.contentCard}>
        <Text style={styles.contentLabel}>Topic Answers</Text>
        <MarkdownRenderer content={note.content} />
      </AppCard>

      <AppButton
        label="Download / Share PDF"
        onPress={handleExportPdf}
        loading={isExporting}
        icon="download"
        style={styles.exportBtn}
      />
    </ScreenWrapper>
  );
}

const styles = StyleSheet.create({
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  header: {
    marginBottom: spacing.md,
  },
  title: {
    ...typography.h2,
    color: colors.text,
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
  },
  provider: {
    ...typography.caption,
    color: colors.textMuted,
    marginBottom: spacing.md,
  },
  summaryCard: {
    padding: spacing.md,
    backgroundColor: colors.primaryLight,
    borderColor: colors.primaryLight,
  },
  summaryLabel: {
    ...typography.caption,
    color: colors.primaryDark,
    fontWeight: '600',
    marginBottom: spacing.xs,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  summaryText: {
    ...typography.bodySmall,
    color: colors.text,
    lineHeight: 22,
  },
  contentCard: {
    padding: spacing.md,
    marginTop: spacing.md,
  },
  contentLabel: {
    ...typography.caption,
    color: colors.textSecondary,
    fontWeight: '600',
    marginBottom: spacing.sm,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  content: {
    ...typography.bodySmall,
    color: colors.text,
    lineHeight: 24,
  },
  exportBtn: {
    marginTop: spacing.lg,
    marginBottom: spacing.xl,
  },
});
