"""Generate study-note PDFs from markdown content."""

from __future__ import annotations

import re
from io import BytesIO

from fpdf import FPDF


def _to_latin1(text: str) -> str:
    text = text.replace("•", "-")
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _strip_markdown(text: str) -> str:
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.M)
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    text = re.sub(r"^\s*[-*]\s+", "- ", text, flags=re.M)
    return text.strip()


def _write_line(pdf: FPDF, text: str, *, bold: bool = False, size: int = 11) -> None:
    if not text.strip():
        pdf.ln(4)
        return
    style = "B" if bold else ""
    pdf.set_font("Helvetica", style, size)
    pdf.multi_cell(pdf.epw, 6, _to_latin1(text))


def generate_note_pdf_bytes(
    title: str,
    content: str,
    *,
    subject: str | None = None,
    topics: list[str] | None = None,
) -> bytes:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(18, 18, 18)
    pdf.add_page()

    _write_line(pdf, title, bold=True, size=18)
    pdf.ln(2)

    if subject:
        _write_line(pdf, f"Subject: {subject}", size=11)
        pdf.ln(1)

    if topics:
        pdf.set_font("Helvetica", "I", 10)
        pdf.multi_cell(pdf.epw, 5, _to_latin1("Topics: " + ", ".join(topics[:20])))
        pdf.ln(4)

    pdf.set_draw_color(200, 200, 200)
    y = pdf.get_y()
    pdf.line(18, y, pdf.w - 18, y)
    pdf.ln(6)

    plain = _strip_markdown(content)
    for raw_line in plain.splitlines():
        line = raw_line.strip()
        if not line:
            pdf.ln(3)
            continue

        if line.startswith("```"):
            continue

        if line.startswith("## "):
            pdf.ln(4)
            _write_line(pdf, line[3:].strip(), bold=True, size=13)
            pdf.ln(1)
            continue

        if line.startswith("### "):
            pdf.ln(2)
            _write_line(pdf, line[4:].strip(), bold=True, size=11)
            continue

        _write_line(pdf, line, size=11)

    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(pdf.epw, 5, "Generated by SmartStudy - AI-powered exam notes")

    buffer = BytesIO()
    pdf.output(buffer)
    return buffer.getvalue()
