"""ExamBuddy exam-oriented notes schema (v19)."""

from __future__ import annotations

PROMPT_VERSION = "v19.0"

EXAM_NOTE_FIELDS = (
    "topic",
    "topicType",
    "definition",
    "introduction",
    "detailedExplanation",
    "keyConcepts",
    "working",
    "diagram",
    "example",
    "advantages",
    "disadvantages",
    "applications",
    "formulae",
    "frequentlyAskedQuestions",
    "twoMarkAnswer",
    "fiveMarkAnswer",
    "tenMarkAnswer",
    "vivaQuestions",
    "interviewQuestions",
    "commonMistakes",
    "revisionSummary",
    "keywords",
    # Optional / category-specific extras kept when present
    "characteristics",
    "architecture",
    "syntax",
    "codeExample",
    "output",
    "pseudocode",
    "timeComplexity",
    "spaceComplexity",
    "comparison",
)

# Map aliases (including Professor Alex v18) into canonical v19 fields.
FIELD_ALIASES: dict[str, tuple[str, ...]] = {
    "topicType": ("topicType", "category", "type"),
    "definition": ("definition", "whatIsIt"),
    "introduction": ("introduction", "whyNeeded", "whyItMatters", "whyUsed"),
    "detailedExplanation": ("detailedExplanation", "deepDive", "coreConcept"),
    "keyConcepts": ("keyConcepts", "components", "characteristics", "features"),
    "working": ("working", "howItWorks", "workingPrinciple", "stepByStep", "flow"),
    "diagram": ("diagram",),
    "example": ("example", "examples", "realWorldExample", "real_world_example"),
    "advantages": ("advantages",),
    "disadvantages": ("disadvantages",),
    "applications": ("applications",),
    "formulae": ("formulae", "formulas", "importantFormulae", "formula"),
    "frequentlyAskedQuestions": (
        "frequentlyAskedQuestions",
        "examQuestions",
        "universityQuestions",
    ),
    "twoMarkAnswer": ("twoMarkAnswer", "two_mark_answer", "answer2Mark"),
    "fiveMarkAnswer": ("fiveMarkAnswer", "five_mark_answer", "answer5Mark"),
    "tenMarkAnswer": ("tenMarkAnswer", "ten_mark_answer", "answer10Mark"),
    "vivaQuestions": ("vivaQuestions", "viva_questions"),
    "interviewQuestions": ("interviewQuestions", "interview_questions"),
    "commonMistakes": ("commonMistakes", "common_mistakes"),
    "revisionSummary": (
        "revisionSummary",
        "revisionSheet",
        "thirtySecondRevision",
        "summary",
        "keyTakeaways",
    ),
    "keywords": ("keywords", "keyPoints"),
    "characteristics": ("characteristics",),
    "architecture": ("architecture",),
    "syntax": ("syntax",),
    "codeExample": ("codeExample", "code", "code_example"),
    "output": ("output",),
    "pseudocode": ("pseudocode", "pseudoCode"),
    "timeComplexity": ("timeComplexity", "time_complexity"),
    "spaceComplexity": ("spaceComplexity", "space_complexity"),
    "comparison": ("comparison", "table"),
}
